"""tabela_de_funcionarios

Revision ID: 4e05af08790c
Revises: 
Create Date: 2021-01-15 15:30:16.357621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e05af08790c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('armamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_arma', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('valor', sa.String(length=11), nullable=True),
    sa.Column('cartucho', sa.String(length=15), nullable=True),
    sa.Column('penetrabilidade', sa.String(length=15), nullable=True),
    sa.Column('cadência_de_tiro', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codinome', sa.String(length=20), nullable=True),
    sa.Column('data_de_nascimento', sa.String(length=11), nullable=True),
    sa.Column('cpf', sa.String(length=15), nullable=True),
    sa.Column('rg', sa.String(length=15), nullable=True),
    sa.Column('estado_civil', sa.String(length=30), nullable=True),
    sa.Column('escolaridade', sa.String(length=50), nullable=True),
    sa.Column('endereço', sa.String(length=70), nullable=True),
    sa.Column('habilidades', sa.String(length=60), nullable=True),
    sa.Column('celular', sa.String(length=12), nullable=True),
    sa.Column('email', sa.String(length=25), nullable=True),
    sa.Column('salario', sa.String(length=20), nullable=True),
    sa.Column('missoes_presente', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_missao', sa.String(length=100), nullable=False),
    sa.Column('data', sa.String(length=20), nullable=True),
    sa.Column('local', sa.String(length=11), nullable=True),
    sa.Column('cliente', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('arsenal', sa.String(length=20), nullable=True),
    sa.Column('agentes_responsaveis', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missao')
    op.drop_table('funcionario')
    op.drop_table('armamento')
    # ### end Alembic commands ###
